version: 2
updates:
  - package-ecosystem: npm
    directory: /ui
    schedule:
      interval: weekly
  - package-ecosystem: gradle
    directory: /bff
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
